# Generated by Django 5.2.9 on 2025-12-13 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_type', models.CharField(choices=[('collage', '1x3 Collage'), ('gif', 'Animated GIF')], max_length=10)),
                ('user_message', models.CharField(blank=True, max_length=200)),
                ('final_file', models.FileField(upload_to='captures/')),
            ],
        ),
    ]
