# Generated by Django 5.2.9 on 2025-12-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='individual_photos/')),
                ('index', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photobooth.photosession')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('session', 'index')},
            },
        ),
    ]
