# Generated by Django 5.2.9 on 2026-04-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0002_individualphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosession',
            name='chosen_template',
            field=models.CharField(default='photostrip_1.jpg', max_length=50),
        ),
    ]
