# Generated by Django 5.2.9 on 2026-04-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0003_photosession_chosen_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosession',
            name='session_type',
            field=models.CharField(choices=[('collage', 'Photostrip Collage'), ('gif', 'Animated GIF')], max_length=10),
        ),
    ]
